server:
  port: 8084

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
